#include "Array.hpp"

int main(void)
{
	Array<int> a;
	
	try
	{
		/* code */
	}
	catch(const std::exception& e)
	{
		std::cerr << e.what() << '\n';
	}
	
}